name: Lint, test and build

on:
  pull_request:
    branches:
      - 'development'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

  lint-test-build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm i --legacy-peer-deps

      - name: Run nx lint
        run: npm run lint

      - name: Run nx test
        run: npm run test

      - name: Run nx build
        run: npm run build
